// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_tXU_PnVqddERwAo3S00PeZn-sa-Jy50',
    appId: '1:397646864507:web:ec48c5042ddaaa123b82de',
    messagingSenderId: '397646864507',
    projectId: 'reddit-8d41d',
    authDomain: 'reddit-8d41d.firebaseapp.com',
    storageBucket: 'reddit-8d41d.appspot.com',
    measurementId: 'G-5QD62NH2CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkbyC40JvcaKwRw8sV4R1xeGN7sXcSax8',
    appId: '1:397646864507:android:d860c17f76589ddf3b82de',
    messagingSenderId: '397646864507',
    projectId: 'reddit-8d41d',
    storageBucket: 'reddit-8d41d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk67521qZ31LUHhLHKpy7sxF4yhCngNck',
    appId: '1:397646864507:ios:65158b3020ee8d543b82de',
    messagingSenderId: '397646864507',
    projectId: 'reddit-8d41d',
    storageBucket: 'reddit-8d41d.appspot.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk67521qZ31LUHhLHKpy7sxF4yhCngNck',
    appId: '1:397646864507:ios:c668ebb999ccebe13b82de',
    messagingSenderId: '397646864507',
    projectId: 'reddit-8d41d',
    storageBucket: 'reddit-8d41d.appspot.com',
    iosBundleId: 'com.example.reddit.RunnerTests',
  );
}
